language: node_js
node_js:
  - "5.7.0"
script:
  - "node node_modules/pxt-core/built/pxt.js travis"  
  - "node node_modules/pxt-core/built/pxt.js testdir tests"
sudo: false
notifications:
  email:
    - kindscript@microsoft.com
cache:
  directories:
    - node_modules
    - built/cache
    - libs/hello/built/cache
