namespace images {
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const butterfly1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const butterfly2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const cat1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const cat2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const check = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const dog1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const dog2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const down = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const eyes1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const eyes2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const eyes3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const eyes4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const floppy1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const floppy2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const frown = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const globe = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const go = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const heart1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const heart2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const hSign = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const iSign = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const left = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const logo = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const logo1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const no = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const right = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const smile = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const soccerBall = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const stegosaurus = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const stop = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const trex = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const triceratop = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const up = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const walker1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const walker2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const walker3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const walker4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images.showImage
    //% tags="images"
    export const x_copy = image.ofBuffer(hex``);
}
