namespace images {
    //% fixedInstance jres blockIdentity=images._image
    export const butterfly1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const butterfly2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const cat1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const cat2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const chicken = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const cow = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const dog1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const dog2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const eyes1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const eyes2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const eyes3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const eyes4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const floppy1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const floppy2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const frown = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const globe = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const go = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const hSign = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const iSign = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const pig = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smile = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const soccerBall = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const stegosaurus = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const stop = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const trex = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const triceratop = image.ofBuffer(hex``);
}
